"""
state.py
Input/output state for the Frontend LLD Agent.

In the real flow this agent receives 3 inputs from the supervisor:
  - user_input       : original user prompt (e.g. "one-page marketing website")
  - requirement_doc  : generated by the System Analyst Agent
  - architecture_doc : generated by the Architecture Agent

Output:
  - frontend_lld : the generated Frontend LLD document
"""
from typing import TypedDict


class FrontendLLDState(TypedDict):
    user_input: str
    requirement_doc: str
    architecture_doc: str
    frontend_lld: str


# ── Sample inputs for standalone testing (python app.py) ─────────────────────

SAMPLE_USER_INPUT = "Create a one-page marketing website for a business."

SAMPLE_REQUIREMENT_DOC = """
# Requirements Document: One-Page Marketing Website

## Functional Requirements
- Display business services (minimum 3, maximum 6)
- Show company background in an About section
- Provide contact details with embedded map
- Smooth scroll navigation between sections
- Mobile and desktop responsive layout

## Non-Functional Requirements
- Fast page load using Static Site Generation
- SEO optimized with proper metadata
- Accessible across all screen sizes

## Constraints
- All content is static — no CMS required
- Must use Next.js as the framework
- Must use Tailwind CSS for styling
"""

SAMPLE_ARCHITECTURE_DOC = """
# Architecture Document: One-Page Marketing Website

## Architecture Pattern
Component-Based Modular Monolithic

## Application Type
Single-Page Application (SPA)

## Rendering Strategy
Static Site Generation (SSG) — content is pre-rendered at build time

## Sub Systems
1. Presentation Layer – Navigation, Hero, About, Services, Location/Contact, Footer
2. Content Management – static data stored inside the application as constants
3. Styling / UI Framework – Tailwind CSS 4.0, mobile-first responsive design
4. Optimization Layer – image optimization, metadata management, SEO tags

## Technology Stack
| Technology            | Version | Purpose                  |
|-----------------------|---------|--------------------------|
| Next.js               | ^15.0   | Main web framework       |
| React                 | ^19.0   | UI component library     |
| TypeScript            | ^5.0    | Type safety              |
| Tailwind CSS          | ^4.0    | Responsive styling       |
| Node.js               | ^20.x   | Runtime environment      |
| Google Maps Embed API | Latest  | Location map integration |
| Vercel                | Latest  | Deployment platform      |

## Constraints
- Single-page vertical scroll layout
- Services section: minimum 3, maximum 6 items
- All content initially static within the application
- Must include proper HTML structure and metadata for SEO
"""