import os
from datetime import date
from pathlib import Path
from typing_extensions import TypedDict
from dotenv import load_dotenv
from langchain.agents import create_agent
from langchain_groq import ChatGroq
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import StateGraph, START, END


# ----------------------------
# 1. Define Shared State
# ----------------------------

class State(TypedDict):
    question: str
    supervisor_prompt: str
    research_data: str
    final_answer: str


# Load environment variables from local .env if available.
env_path = Path(__file__).parent / ".env"
load_dotenv(dotenv_path=env_path)

groq_api_key = os.getenv("GROQ_API_KEY")
if not groq_api_key:
    raise ValueError(f"GROQ_API_KEY not found. Checked .env at: {env_path}")

llm = ChatGroq(model="llama-3.3-70b-versatile", api_key=groq_api_key)


@tool
def get_current_date() -> str:
    """Return today's date in ISO format (YYYY-MM-DD)."""
    return date.today().isoformat()


research_tools = [get_current_date]
research_react_agent = create_agent(model=llm, tools=research_tools)


# ----------------------------
# 2. Research Agent (Subgraph)
# ----------------------------

def research_node(state: State):
    question = state["question"]
    supervisor_prompt = state["supervisor_prompt"]

    research_prompt = (
        "You are a domain-flexible research agent in a multi-agent system. "
        "Handle any topic: technical, scientific, business, legal, educational, creative, or everyday queries. "
        "Identify the intent of the user question, gather only relevant information, and avoid unnecessary detail. "
        "If time, place, or current events matter, use available tools when helpful and clearly separate tool-derived facts from model knowledge. "
        "Return concise bullet-point research notes with short caveats where uncertainty exists."
    )

    response = research_react_agent.invoke(
        {
            "messages": [
                ("system", research_prompt),
                (
                    "human",
                    f"Supervisor Instructions:\n{supervisor_prompt}\n\nUser Question:\n{question}",
                ),
            ]
        }
    )

    messages = response.get("messages", []) if isinstance(response, dict) else []
    research_result = ""
    for msg in reversed(messages):
        if getattr(msg, "type", "") == "ai":
            research_result = str(getattr(msg, "content", "")).strip()
            break

    if not research_result:
        research_result = "No research output generated by ReAct agent."

    print("Research Agent working...")

    return {"research_data": research_result}


research_builder = StateGraph(State)

research_builder.add_node("research_node", research_node)
research_builder.add_edge(START, "research_node")
research_builder.add_edge("research_node", END)

research_subgraph = research_builder.compile()


# ----------------------------
# 3. Summarizer Agent (Subgraph)
# ----------------------------

def summarize_node(state: State):
    research = state["research_data"]
    question = state["question"]
    supervisor_prompt = state["supervisor_prompt"]

    print("Summarizer Agent working...")

    summary_prompt = (
        "You are a domain-flexible summarizer agent. "
        "Create a clear final answer from the research notes for any topic and audience. "
        "Start with a direct answer in plain language, then include a short 'Key Points' section. "
        "If the research includes uncertainty, assumptions, or missing data, state them briefly and explicitly."
    )

    summary_response = llm.invoke(
        [
            SystemMessage(content=summary_prompt),
            HumanMessage(
                content=(
                    f"Supervisor Instructions:\n{supervisor_prompt}\n\n"
                    f"User Question:\n{question}\n\n"
                    f"Research Notes:\n{research}"
                )
            ),
        ]
    )

    summary = summary_response.content

    return {"final_answer": summary}


summary_builder = StateGraph(State)

summary_builder.add_node("summarize_node", summarize_node)
summary_builder.add_edge(START, "summarize_node")
summary_builder.add_edge("summarize_node", END)

summary_subgraph = summary_builder.compile()


# ----------------------------
# 4. Supervisor Agent
# ----------------------------

def supervisor_node(state: State):

    print("Supervisor received question:", state["question"])

    supervisor_prompt = (
        "Role: Supervisor Agent\n"
        "Goal: Coordinate research and summarization to answer any user question clearly and accurately.\n"
        "Instructions:\n"
        "1. Detect the question type (factual, analytical, procedural, comparative, creative, or mixed) and adapt depth accordingly.\n"
        "2. Ensure the research agent captures only information that is directly useful for answering the question.\n"
        "3. Prevent fabrication; when evidence is limited or ambiguous, require explicit uncertainty statements.\n"
        "4. Ask the summarizer to provide a direct answer first, then key supporting points and practical next steps when appropriate.\n"
        "5. Keep output concise, structured, and easy for non-experts to understand unless the user asks for advanced detail."
    )

    return {"supervisor_prompt": supervisor_prompt}


# ----------------------------
# 5. Build Main Multi-Agent Graph
# ----------------------------

builder = StateGraph(State)

# Supervisor
builder.add_node("supervisor", supervisor_node)

# Subgraph agents
builder.add_node("research_agent", research_subgraph)
builder.add_node("summary_agent", summary_subgraph)

# Flow
builder.add_edge(START, "supervisor")
builder.add_edge("supervisor", "research_agent")
builder.add_edge("research_agent", "summary_agent")
builder.add_edge("summary_agent", END)

graph = builder.compile()


# ----------------------------
# 6. Run the System
# ----------------------------

result = graph.invoke({
    
    "question": "what is the current date and weather in kochi",
    "supervisor_prompt": "",
    "research_data": "",
    "final_answer": ""
})

print("\nFinal Output:")
final_answer = str(result.get("final_answer", "")).strip()
if final_answer:
    print(final_answer)
else:
    print("No final_answer returned. Full graph state:")
    print(result)
